name: API Tests

on:
  push:
    branches: [main, develop]
    paths: ['api/**']
  pull_request:
    branches: [main, develop]
    paths: ['api/**']

jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: api
          name: api-coverage

      - name: Build
        run: go build -v -o bin/api ./cmd/api 
