name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    name: Web (/web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Typecheck
        run: bun run check

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build

      - name: Upload build artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            build/**
          if-no-files-found: ignore

  docker-preview:
    name: Docker build (no push)
    runs-on: ubuntu-latest
    needs: [web]
    if: ${{ github.event_name == 'pull_request' && startsWith(github.base_ref, 'main') || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (web)
        uses: docker/build-push-action@v6
        with:
          context: web
          file: web/Dockerfile
          push: false
          platforms: linux/amd64

  docker-publish:
    name: Docker publish (GHCR)
    runs-on: ubuntu-latest
    needs: [web]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tags
        id: meta
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT
          echo "sha_tag=ghcr.io/${REPO_LOWER}:web-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "latest_tag=ghcr.io/${REPO_LOWER}:web-latest" >> $GITHUB_OUTPUT

      - name: Build and push (web)
        uses: docker/build-push-action@v6
        with:
          context: web
          file: web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.sha_tag }},${{ steps.meta.outputs.latest_tag }}
          platforms: linux/amd64
